services:
  - type: web
    name: frank-api
    runtime: python
    rootDir: apps
    buildCommand: pip install -r api/requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    plan: free
